### ISSUE TITLE
Comments into type Query and type Mutation breaks highlight.

### ISSUE THREAD

**Issue by carlitux** [bkegley/tree-sitter-graphql#2]
With comment/description
![Screenshot from 2020-11-27 12-45-41](https://user-images.githubusercontent.com/40538/100470417-978d6180-30ae-11eb-9f42-b3e826e2ef5f.png)

Without comment/description
![Screenshot from 2020-11-27 12-45-58](https://user-images.githubusercontent.com/40538/100470419-98be8e80-30ae-11eb-90d6-3720c6d343a6.png)

**Comment by bkegley** [comment]
Good catch! Should be fixed now!
